require('dotenv').config()

const fs = require('fs')
const path = require('path')
const LRU = require('lru-cache')
const express = require('express')
const favicon = require('serve-favicon')
const compression = require('compression')
const microcache = require('route-cache')
const http = require('http')
const resolve = file => path.resolve(__dirname, file)
const { createBundleRenderer } = require('vue-server-renderer')


var hush = require('bitcoin');

var client = new hush.Client({
  host: process.env.RPC_HOST,
  port: process.env.RPC_PORT,
  user: process.env.RPC_USER,
  pass: process.env.RPC_PASSWORD,
  timeout: 30000
});

const isProd = process.env.NODE_ENV === 'production'
const useMicroCache = process.env.MICRO_CACHE !== 'false'
const serverInfo =
  `express/${require('express/package.json').version} ` +
  `vue-server-renderer/${require('vue-server-renderer/package.json').version}`

const app = express()

function createRenderer (bundle, options) {
  // https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/README.md#why-use-bundlerenderer
  return createBundleRenderer(bundle, Object.assign(options, {
    // for component caching
    cache: LRU({
      max: 1000,
      maxAge: 1000 * 60 * 15
    }),
    // this is only needed when vue-server-renderer is npm-linked
    basedir: resolve('./dist'),
    // recommended for performance
    runInNewContext: false
  }))
}

let renderer
let readyPromise
const templatePath = resolve('./src/index.template.html')
if (isProd) {
  // In production: create server renderer using template and built server bundle.
  // The server bundle is generated by vue-ssr-webpack-plugin.
  const template = fs.readFileSync(templatePath, 'utf-8')
  const bundle = require('./dist/vue-ssr-server-bundle.json')
  // The client manifests are optional, but it allows the renderer
  // to automatically infer preload/prefetch links and directly add <script>
  // tags for any async chunks used during render, avoiding waterfall requests.
  const clientManifest = require('./dist/vue-ssr-client-manifest.json')
  renderer = createRenderer(bundle, {
    template,
    clientManifest
  })
} else {
  // In development: setup the dev server with watch and hot-reload,
  // and create a new renderer on bundle / index template update.
  readyPromise = require('./build/setup-dev-server')(
    app,
    templatePath,
    (bundle, options) => {
      renderer = createRenderer(bundle, options)
    }
  )
}

const serve = (path, cache) => express.static(resolve(path), {
  maxAge: cache && isProd ? 1000 * 60 * 60 * 24 * 30 : 0
})

app.use(compression({ threshold: 0 }))
app.use(favicon('./public/logo-48.png'))
app.use('/dist', serve('./dist', true))
app.use('/public', serve('./public', true))
app.use('/manifest.json', serve('./manifest.json', true))
app.use('/service-worker.js', serve('./dist/service-worker.js'))

// since this app has no user-specific content, every page is micro-cacheable.
// if your app involves user-specific content, you need to implement custom
// logic to determine whether a request is cacheable based on its url and
// headers.
// 1-second microcache.
// https://www.nginx.com/blog/benefits-of-microcaching-nginx/
app.use(microcache.cacheSeconds(1, req => useMicroCache && req.originalUrl))

function render (req, res) {
  const s = Date.now()

  res.setHeader("Content-Type", "text/html")
  res.setHeader("Server", serverInfo)

  const handleError = err => {
    if (err.url) {
      res.redirect(err.url)
    } else if(err.code === 404) {
      res.status(404).send('404 | Page Not Found')
    } else {
      // Render Error Page or Redirect
      res.status(500).send('500 | Internal Server Error')
      console.error(`error during render : ${req.url}`)
      console.error(err.stack)
    }
  }

  const context = {
    title: 'Vue HN 2.0', // default title
    url: req.url
  }
  renderer.renderToString(context, (err, html) => {
    if (err) {
      return handleError(err)
    }
    res.send(html)
    if (!isProd) {
      console.log(`whole request: ${Date.now() - s}ms`)
    }
  })
}


app.get('/top', isProd ? render : (req, res) => {
  readyPromise.then(() => render(req, res))
})

app.get('/api/blockcount', (req, res) => {
  client.cmd('getblockcount', function(err, blockcount, resHeaders){
    if (err) return console.log(err);
    res.json({message: blockcount});
  });
});

// const server = new http.Server(app);
//
// var io = require('socket.io').listen(app);


const port = process.env.PORT || 8080

const server = new http.Server(app);
const io = require('socket.io')(server);

// const WS_PORT = process.env.PORT || 8090;
const WS_PORT = 8090;

// server.listen(WS_PORT);

io.on('connection', (socket) => {
  // <insert relevant code here>
  socket.on('pingServer', function(data) {
    console.log('WS event sent');
  });

  //send data to client
  setInterval(function(){

    // Block Height
    client.cmd('getblockcount', function(err, blockHeight, resHeaders){
      if (err) return console.log(err);
      socket.emit('blockHeight', blockHeight);
    });

    // Circulation
    // client.cmd('gettxoutsetinfo', function(err, data, resHeaders) {
    //   if (err) return console.log(err);
    //   socket.emit('circulation', data.total_amount);
    // })

  }, 15000);

  console.log('SOCKET connection');
});


// app.listen(port, () => {
//   console.log(`server started at localhost:${port}`)
// })
+app.listen(port,'0.0.0.0')
